version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install --force
      - npm run build
      - cp Procfile dist/ # Copy Procfile to the build output directory
      - cp package.json dist/ # Copy package.json to the build output directory
  build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: dist
